//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffeeHouse_TCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNT
    {
        public string MAGIAMGIA { get; set; }
        public Nullable<int> PHANTRAMGIAM { get; set; }
        public Nullable<double> SOTIENGIAM { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    }
}
