//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffeeHouse_TCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ACCOUNT_EMPLOYEE = new HashSet<ACCOUNT_EMPLOYEE>();
        }
    
        public string MANV { get; set; }
        public string TENNV { get; set; }
        public Nullable<System.DateTime> NGAYSINHNV { get; set; }
        public string DIACHINV { get; set; }
        public string SDT_NV { get; set; }
        public string EMAIL { get; set; }
        public string GIOITINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_EMPLOYEE> ACCOUNT_EMPLOYEE { get; set; }
    }
}
