//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffeeHouse_TCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public string MATHANHTOAN { get; set; }
        public string VNPAY { get; set; }
        public string TIENMAT { get; set; }
        public string MOMO { get; set; }
        public string ZALOPAY { get; set; }
        public string SHOPPEEPAY { get; set; }
        public string THENGANHANG { get; set; }
    
        public virtual OrderPro OrderPro { get; set; }
    }
}
