//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffeeHouse_TCH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string MASP { get; set; }
        public string MAKH { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public string MATHANHTOAN { get; set; }
    
        public virtual OrderPro OrderPro { get; set; }
        public virtual Product Product { get; set; }
    }
}
